

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_db
    username: admin
    password: pwd1234
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create

